import { parseAbi } from "viem";

export const ZEROXN_ADDRESS = "0x5C833AAef51A680F49CeC2E16B585409d07c638B" as const;

export const ZEROXN_ABI = parseAbi([
  "function NUSD() view returns (address)",
  "function pixel() view returns (address)",
  "function paused() view returns (bool)",
  "function postCount() view returns (uint256)",
  "function commentCount() view returns (uint256)",
  "function channelCount() view returns (uint256)",
  "function groupCount() view returns (uint256)",
  "function messageCount() view returns (uint256)",
  "function minVerifiedPostLikes() view returns (uint256)",
  "function minVerifiedFollowers() view returns (uint256)",
  "function minVerifiedNUSDBalance() view returns (uint256)",
  "function profiles(address user) view returns (string username, string displayName, string bio, uint256 avatarTokenId, bool avatarEnabled, bool exists, bool adminVerified, uint64 createdAt, uint64 updatedAt)",
  "function usernameOwner(bytes32 usernameHash) view returns (address)",
  "function posts(uint256 postId) view returns (address author, uint256 channelId, uint256 pixelTokenId, string content, uint64 createdAt, uint32 likeCount, uint32 commentCount, bool hasPixel, bool deleted)",
  "function comments(uint256 commentId) view returns (uint256 postId, address author, uint256 pixelTokenId, string content, uint64 createdAt, bool hasPixel, bool deleted)",
  "function channels(uint256 channelId) view returns (address creator, string slug, string name, string description, uint64 createdAt, uint32 memberCount, bool active)",
  "function groups(uint256 groupId) view returns (address creator, string name, string description, uint64 createdAt, uint32 memberCount, uint32 messageCount, bool active)",
  "function messages(uint256 messageId) view returns (address from, address to, uint256 groupId, string content, bytes encryptedPayload, uint64 createdAt, uint8 kind, bool deleted)",
  "function likedPost(uint256 postId, address user) view returns (bool)",
  "function following(address follower, address target) view returns (bool)",
  "function channelMember(uint256 channelId, address user) view returns (bool)",
  "function groupMember(uint256 groupId, address user) view returns (bool)",
  "function groupAdmin(uint256 groupId, address user) view returns (bool)",
  "function groupOfficer(uint256 groupId, address user) view returns (bool)",
  "function groupRankName(uint256 groupId, address user) view returns (string)",
  "function groupKeyEnvelope(uint256 groupId, address user) view returns (bytes)",
  "function followerCount(address user) view returns (uint256)",
  "function followingCount(address user) view returns (uint256)",
  "function maxPostLikes(address user) view returns (uint256)",
  "function isVerified(address user) view returns (bool)",
  "function isAvatarValid(address user) view returns (bool)",
  "function getUserPosts(address user, uint256 offset, uint256 limit) view returns (uint256[])",
  "function getChannelPosts(uint256 channelId, uint256 offset, uint256 limit) view returns (uint256[])",
  "function getPostComments(uint256 postId, uint256 offset, uint256 limit) view returns (uint256[])",
  "function getGroupMessages(uint256 groupId, uint256 offset, uint256 limit) view returns (uint256[])",
  "function getGlobalMessages(uint256 offset, uint256 limit) view returns (uint256[])",
  "function getInbox(address user, uint256 offset, uint256 limit) view returns (uint256[])",
  "function getSent(address user, uint256 offset, uint256 limit) view returns (uint256[])",
  "function registerProfile(string username, string displayName, string bio, bool avatarEnabled, uint256 avatarTokenId)",
  "function updateProfile(string displayName, string bio, bool avatarEnabled, uint256 avatarTokenId)",
  "function changeUsername(string newUsername)",
  "function createPost(string content, bool hasPixel, uint256 pixelTokenId) returns (uint256)",
  "function joinChannel(uint256 channelId)",
  "function leaveChannel(uint256 channelId)",
  "function postToChannel(uint256 channelId, string content, bool hasPixel, uint256 pixelTokenId) returns (uint256)",
  "function commentOnPost(uint256 postId, string content, bool hasPixel, uint256 pixelTokenId) returns (uint256)",
  "function likePost(uint256 postId)",
  "function follow(address target)",
  "function unfollow(address target)",
  "function createChannel(string slug, string name, string description) returns (uint256)",
  "function createGroup(string name, string description, bytes creatorKeyEnvelope) returns (uint256)",
  "function addGroupMember(uint256 groupId, address member, bytes keyEnvelope)",
  "function removeGroupMember(uint256 groupId, address member)",
  "function leaveGroup(uint256 groupId)",
  "function setGroupAdmin(uint256 groupId, address admin, bool enabled)",
  "function setGroupOfficer(uint256 groupId, address officer, bool enabled, string rankName)",
  "function setGroupKeyEnvelope(uint256 groupId, address member, bytes keyEnvelope)",
  "function sendPublicMessage(string content) returns (uint256)",
  "function sendGroupMessage(uint256 groupId, bytes encryptedPayload) returns (uint256)",
  "function sendEncryptedMessage(address to, bytes encryptedPayload) returns (uint256)",
  "event ProfileCreated(address indexed user, string username)",
  "event ProfileUpdated(address indexed user)",
  "event UsernameChanged(address indexed user, string oldUsername, string newUsername)",
  "event AdminVerified(address indexed user, bool verified)",
  "event PostCreated(uint256 indexed postId, address indexed author, uint256 indexed channelId, uint256 pixelTokenId)",
  "event PostDeleted(uint256 indexed postId)",
  "event PostLiked(uint256 indexed postId, address indexed user, address indexed author, uint256 likeCount)",
  "event CommentCreated(uint256 indexed commentId, uint256 indexed postId, address indexed author)",
  "event CommentDeleted(uint256 indexed commentId)",
  "event Followed(address indexed follower, address indexed target)",
  "event Unfollowed(address indexed follower, address indexed target)",
  "event ChannelCreated(uint256 indexed channelId, string slug, address indexed creator)",
  "event ChannelJoined(uint256 indexed channelId, address indexed user)",
  "event ChannelLeft(uint256 indexed channelId, address indexed user)",
  "event ChannelStatusUpdated(uint256 indexed channelId, bool active)",
  "event GroupCreated(uint256 indexed groupId, address indexed creator)",
  "event GroupMemberAdded(uint256 indexed groupId, address indexed member, address indexed addedBy)",
  "event GroupMemberRemoved(uint256 indexed groupId, address indexed member, address indexed removedBy)",
  "event GroupAdminUpdated(uint256 indexed groupId, address indexed admin, bool enabled)",
  "event GroupOfficerUpdated(uint256 indexed groupId, address indexed officer, bool enabled, string rankName)",
  "event GroupKeyEnvelopeUpdated(uint256 indexed groupId, address indexed member)",
  "event GroupStatusUpdated(uint256 indexed groupId, bool active)",
  "event MessageSent(uint256 indexed messageId, uint8 indexed kind, address indexed from, address to, uint256 groupId)",
  "event MessageDeleted(uint256 indexed messageId)",
]);

export type ZeroxNProfile = readonly [
  string,
  string,
  string,
  bigint,
  boolean,
  boolean,
  boolean,
  bigint,
  bigint,
];

export type ZeroxNPost = readonly [
  `0x${string}`,
  bigint,
  bigint,
  string,
  bigint,
  number,
  number,
  boolean,
  boolean,
];

export type ZeroxNComment = readonly [
  bigint,
  `0x${string}`,
  bigint,
  string,
  bigint,
  boolean,
  boolean,
];

export type ZeroxNChannel = readonly [
  `0x${string}`,
  string,
  string,
  string,
  bigint,
  number,
  boolean,
];

export type ZeroxNGroup = readonly [
  `0x${string}`,
  string,
  string,
  bigint,
  number,
  number,
  boolean,
];

export type ZeroxNMessage = readonly [
  `0x${string}`,
  `0x${string}`,
  bigint,
  string,
  `0x${string}`,
  bigint,
  number,
  boolean,
];
