export const PREDICTION_ADDRESS: `0x${string}` = "0x4B323Ac40FBC6Fb18Cf7e42f851C553390f920AD";

export const PREDICTION_ASSETS = [
  "BTC/USD",
  "ETH/USD",
  "LTC/USD",
  "USDC/USD",
  "XAU/USD",
  "XAG/USD",
  "WTI/USD",
  "XBR/USD",
] as const;

export const PREDICTION_ABI = [
  {
    inputs: [
      { internalType: "address", name: "nusd", type: "address" },
      { internalType: "address", name: "initialFeeReceiver", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [{ internalType: "string", name: "symbol", type: "string" }],
    name: "assetIdOf",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "assets",
    outputs: [
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "address", name: "feed", type: "address" },
      { internalType: "uint32", name: "heartbeat", type: "uint32" },
      { internalType: "uint32", name: "betWindow", type: "uint32" },
      { internalType: "uint32", name: "staleCancelDelay", type: "uint32" },
      { internalType: "uint256", name: "minBet", type: "uint256" },
      { internalType: "uint256", name: "maxBet", type: "uint256" },
      { internalType: "bool", name: "enabled", type: "bool" },
      { internalType: "bool", name: "exists", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "symbol", type: "string" }],
    name: "canBetNow",
    outputs: [
      { internalType: "bool", name: "canBet", type: "bool" },
      { internalType: "uint80", name: "oracleRoundId", type: "uint80" },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "uint256", name: "updatedAt", type: "uint256" },
      { internalType: "uint256", name: "betDeadline", type: "uint256" },
      { internalType: "uint256", name: "closeTime", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "symbol", type: "string" }],
    name: "getLatestPrice",
    outputs: [
      { internalType: "uint80", name: "oracleRoundId", type: "uint80" },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "uint256", name: "updatedAt", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "roundId", type: "uint256" }],
    name: "getRoundCore",
    outputs: [
      { internalType: "bytes32", name: "assetId", type: "bytes32" },
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "address", name: "feed", type: "address" },
      { internalType: "uint80", name: "startOracleRoundId", type: "uint80" },
      { internalType: "uint80", name: "endOracleRoundId", type: "uint80" },
      { internalType: "uint256", name: "startPrice", type: "uint256" },
      { internalType: "uint256", name: "endPrice", type: "uint256" },
      { internalType: "enum ZeroxPrediction.Outcome", name: "outcome", type: "uint8" },
      { internalType: "bool", name: "settled", type: "bool" },
      { internalType: "bool", name: "cancelled", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "roundId", type: "uint256" }],
    name: "getRoundPools",
    outputs: [
      { internalType: "uint256", name: "upPool", type: "uint256" },
      { internalType: "uint256", name: "downPool", type: "uint256" },
      { internalType: "uint256", name: "feeAmount", type: "uint256" },
      { internalType: "uint256", name: "feeBpsSnapshot", type: "uint256" },
      { internalType: "uint256", name: "minBet", type: "uint256" },
      { internalType: "uint256", name: "maxBet", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "roundId", type: "uint256" }],
    name: "getRoundTimes",
    outputs: [
      { internalType: "uint256", name: "startTime", type: "uint256" },
      { internalType: "uint256", name: "betDeadline", type: "uint256" },
      { internalType: "uint256", name: "closeTime", type: "uint256" },
      { internalType: "uint256", name: "staleCancelTime", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "roundId", type: "uint256" },
      { internalType: "address", name: "user", type: "address" },
    ],
    name: "getPosition",
    outputs: [
      { internalType: "uint256", name: "upAmount", type: "uint256" },
      { internalType: "uint256", name: "downAmount", type: "uint256" },
      { internalType: "bool", name: "claimed", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "roundId", type: "uint256" },
      { internalType: "address", name: "user", type: "address" },
    ],
    name: "getClaimable",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "roundId", type: "uint256" },
      { internalType: "uint256", name: "maxLookback", type: "uint256" },
    ],
    name: "previewSettlementOracleRound",
    outputs: [
      { internalType: "uint80", name: "oracleRoundId", type: "uint80" },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "uint256", name: "updatedAt", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "latestRoundOfAsset",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feeBps",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "enum ZeroxPrediction.Side", name: "side", type: "uint8" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "predict",
    outputs: [{ internalType: "uint256", name: "roundId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "roundId", type: "uint256" }],
    name: "settleLatestRound",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "roundId", type: "uint256" },
      { internalType: "uint256", name: "maxLookback", type: "uint256" },
    ],
    name: "settleLatestRoundWithLookback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "roundId", type: "uint256" }],
    name: "cancelStaleRound",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "roundId", type: "uint256" }],
    name: "claim",
    outputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "address", name: "feed", type: "address" },
      { internalType: "bool", name: "enabled", type: "bool" },
    ],
    name: "setAssetDefault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
